engine:
  speed: 4
  history: 100
  autoclose: False
recorder:
  file: record/test.pickle
  record:
    - webcamCapture
    - clock
  replay:
    - webcamCapture
    - clock
webcam:
  deviceIndex: 0
  width: 640
  height: 480
  dtype: u8
