engine:
  speed: 4
  autoclose: False
recorder:
  file: record/test.pickle
  record:
    - preprocessor
webcam:
  deviceIndex: 2
  width: 640
  height: 480
  dtype: u8
  flip: True
preprocessor:
  finger_idx: 8
markov:
  buffer_size: 70
  max_lost: 15
  min_steps: 15